version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Nginx.Dockerfile
    image: balance/nginx
    container_name: balancer-nginx
    ports:
      - "8096:80"
    networks:
      - internal
    volumes:
      - ./:/var/www/app
      #- ./docker/php/conf.d/custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini
  fpm1:
    build:
      context: .
      dockerfile: ./docker/php/Fpm.Dockerfile
    image: balance/php
    container_name: fpm1
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/www/app
#      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
    networks:
      - internal
#    environment:
#      PHP_IDE_CONFIG: teachers.selector.local
#      XDEBUG_MODE: debug
#      XDEBUG_CONFIG: client_host=host.docker.internal
#      XDEBUG_TRIGGER: 'yes'
  fpm2:
    build:
      context: .
      dockerfile: ./docker/php/Fpm.Dockerfile
    image: balance/php
    container_name: fpm2
    ports:
      - "8081:8081"
    volumes:
      - ./:/var/www/app
      - ./docker/php/conf.d/swoole.ini:/usr/local/etc/php/conf.d/swoole.ini
#      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
    networks:
      - internal
  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - internal

###> doctrine/doctrine-bundle ###
  pgsql:
    build:
      context: .
      dockerfile: ./docker/db/Db.Dockerfile
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - '5496:5432'
    networks:
      - internal
    healthcheck:
      test: ['CMD', 'pg_isready', '-d', '${POSTGRES_DB}', '-U', '${POSTGRES_USER}']
      timeout: 5s
      retries: 5
      #start_period: 60s
    volumes:
      - pgsql_data:/var/lib/postgresql/data:rw

networks:
  internal:

volumes:
###> doctrine/doctrine-bundle ###
  pgsql_data:
###< doctrine/doctrine-bundle ###
